apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  ports:
    - name: master
      port: {{ .Values.masterport  }}
      targetPort: {{ .Values.masterport  }}
      protocol: TCP
    - name: slave
      port: {{ .Values.slaveport }}
      targetPort: {{ .Values.slaveport }}
      protocol: TCP 
      
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
